[tasks.version-up]
script = ['''
version-make up -zr package.json
version-make up -zr public/manifest.json
yarn build
''']

[tasks.version-tag]
script = ['''
git tag v$(version-make show package.json)
''']
