name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set envs
        id: set_envs
        run: |
          echo ::set-output name=appname::github-readme-stats-extension
          echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./js-build/node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('./js-build/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies and build
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        working-directory: ./js-build
        run: |
          yarn
          yarn build
          mkdir pack
          mv dist pack
          zip -r ${APPNAME}-v${VERSION}.zip pack
        env:
          APPNAME: ${{ steps.set_envs.outputs.appname }}
          VERSION: ${{ steps.set_envs.outputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "[Changelog](https://github.com/dalance/procs/blob/master/CHANGELOG.md)"
          files: "*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
